version: '3'

services:
  mygoapp:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: freitaspedros/fullcycle
    container_name: golang
    networks:
      - gonet
    tty: true
    volumes:
      - ./src:/usr/src/app
    ports:
      - 10000:10000

networks:
  gonet:
    driver: bridge
